version: '3.7'

services:
  template:
    image: "template"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3002:3002
    environment:
      - CHOKIDAR_USEPOLLING=true