version: '3.7'
services:
  prototype_mfe1:
    image: prototype_mfe1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - /app/node_modules
    ports:
      - '3002:3002'
    environment:
      - CHOKIDAR_USEPOLLING=true
